name: check for typos

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.rst'

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run typos-action
        uses: crate-ci/typos@v1.29.10
