name: typos

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  check-typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check typos
        uses: crate-ci/typos@master
